flask_home_app/webapp/backend/__init__.py
from flask import Flask, send_from_directory
from flask_sqlalchemy import SQLAlchemy
import os
import json
from flask.json import JSONEncoder
from datetime import date
from pymemcache.client.base import PooledClient

class JSerde(object):
    def deserialize(self, key, value, flags):
        if flags == 1:
            return value.decode("utf-8")
        if flags == 2:
            return json.loads(value.decode("utf-8"))
        raise Exception("Unknown serialization format")

db = SQLAlchemy()
DB_NAME = "database.db"
local_addr = (["192", "168"], ["127", "0"])
memcache = PooledClient("/var/run/memcached/memcached.sock", serde=JSerde())

fake_data = {
    "bikeroom/temp": {"Temperature": -99},
    "balcony/temphumid": {"Temperature": -99, "Humidity": -99},
    "kitchen/temphumidpress": {"Temperature": -99, "Humidity": -99, "Airpressure": -99},
}
fake_status = (-1, -1, -1, -1)

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KET"] = "secret"  # No cookies or anything that tracks users...
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.json_encoder = CustomJSONEncoder
    db.init_app(app)
    create_db(app)
    with app.app_context():
        db.session.execute("PRAGMA foreign_keys=on")

    from .views import views

    # from .auth import auth
    from .datavisualizer import datavisualizer
    from .booking import booking

    app.register_blueprint(views, url_prefix="/")
    # app.register_blueprint(auth, url_prefix="/")
    app.register_blueprint(booking, url_prefix="/booking")
    app.register_blueprint(datavisualizer, url_prefix="/dataviz")

    @app.route("/favicon.ico")
    def favicon():
        return send_from_directory(
            os.path.join(app.root_path, "static"),
            "favicon.ico",
            mimetype="image/vnd.microsoft.icon",
        )

    return app


def create_db(app):
    if not os.path.isfile(DB_NAME):
        from .models import Measurer, Temperature, Humidity, Airpressure, Timestamp, Notes

        db.create_all(app=app)


class CustomJSONEncoder(JSONEncoder):
    def default(self, obj):
        try:
            if isinstance(obj, date):
                return obj.isoformat("T")
            iterable = iter(obj)
        except TypeError:
            pass
        else:
            return list(iterable)
        return JSONEncoder.default(self, obj)

flask_home_app/webapp/backend/views.py
from datetime import datetime
from flask import Blueprint, render_template, request, jsonify
from . import local_addr, db, memcache, fake_data, fake_status
import paho.mqtt.publish as publish
from .models import Notes


views = Blueprint("views", __name__)

@views.route("/")
def home():
    local = request.remote_addr.split(".")[:2] in local_addr
    data = memcache.get("weather_data_home")
    rel_status = memcache.get("relay_status")
    return render_template(
        "index.html",
        title="Home",
        data=data if data else fake_data,
        local=local,
        rel_status=rel_status if data else fake_status,
    )


@views.route("/notes", methods=["GET", "POST"])
def notes():
    local = request.remote_addr.split(".")[:2] in local_addr
    return render_template("notes.html", local=local)


@views.route("/notes/api", methods=["GET", "POST", "PUT", "PATCH", "DELETE"])
def notes_api():
    if request.remote_addr.split(".")[:2] in local_addr:
        try:
            if request.method == "GET":
                count = int(request.args.get("c"))
                if count == Notes.query.count():
                    return ("", 204)
                return jsonify(
                    [
                        {
                            "time": note.time.strftime("%Y %B %d %H:%M"),
                            "time_key": note.time,
                            "text": note.text,
                        }
                        for note in Notes.query.order_by(Notes.time.asc())
                        .offset(count)
                        .limit(10)
                        .all()
                    ]
                )
            elif request.method == "POST":
                value = request.json.get("newpost")
                if isinstance(value, str) and len(value) >= 1:
                    note = Notes(time=datetime.now(), text=value)
                    db.session.add(note)
                    db.session.commit()
                    return jsonify(
                        {
                            "time": note.time.strftime("%Y %B %d %H:%M"),
                            "time_key": note.time,
                            "text": note.text,
                        }
                    )
            elif request.method == "PATCH":
                time_key, text = request.json.get("time_key"), request.json.get("text")
                if isinstance(text, str) and len(text) >= 1:
                    Notes.query.filter_by(time=datetime.fromisoformat(time_key)).first().text = text
                    db.session.commit()
                    return ("", 204)
            elif request.method == "DELETE":
                time_key = request.json.get("time_key")
                if time_key:
                    db.session.delete(
                        Notes.query.filter_by(time=datetime.fromisoformat(time_key)).first()
                    )
                    db.session.commit()
                    return ("", 204)
        except:
            pass
    return ("", 400)


# Everyone can get this data
@views.route("/home_status")
def home_status():
    data = memcache.get("weather_data_home")
    rel_status = memcache.get("relay_status")
    return jsonify(
        {
            "weather_data": data if data else fake_data,
            "relay_status": rel_status if data else fake_status,
        }
    )


# Pinsetup for arduino. Send 0-3
# By pin index 0-3(2-5): 2: Full light, 3: Low Light, 4: HEATER_PIN, 5: Unused
entities = {"alloff": "ALLOFF", "full_light": 0, "low_light": 1, "heater": 2}
commands = {"off": 0, "on": 1}


@views.route("/post_command", methods=["POST"])
def post_command():
    if request.remote_addr.split(".")[:2] in local_addr:
        try:
            ent, com = request.form.get("entity").lower(), request.form.get("command").lower()
            if ent in entities and com in commands:
                pub = (
                    entities[ent]
                    if ent == "alloff"
                    else f'({entities[ent]},{commands[com]},{0 if com == "off" else 5 if ent == "full_light" else 420})'
                )
                publish.single("home/balcony/relay/command", pub, hostname="www.home")
                return ("", 204)
        except:
            pass
    return ("", 400)

flask_home_app/webapp/backend/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">{%
    endblock %}{% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />{% endblock %}{% block header %}{% endblock
    %}
    <title>{% block title %}Base{% endblock %}</title>
</head>

<body style="font-size: 20px;">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="text-light btn btn-secondary m-1 btn-lg" href="/">Home</a>
                <a class="text-light btn btn-secondary m-1 btn-lg" href="{{ url_for('datavisualizer.home') }}">Data
                    Graphs</a>
                <a class="text-light btn btn-secondary m-1 btn-lg" href="{{ url_for('views.notes') }}">Notes</a>
                <a class="text-light btn btn-secondary m-1 btn-lg" href="{{ url_for('booking.home') }}">Booking</a>
            </div>
        </div>
    </nav>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">{% block footer %}{% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>{% block script %}{%endblock %}
</body>

</html>

flask_home_app/webapp/backend/templates/index.html
{% extends "base.html" %} {% block header %}
<style>
    .success {
        color: #3d9b3f;
        background-color: #c1e6b4;
        border-color: #d6e9c6;
        display: none;
    }

    .col1 {
        width: 14rem;
    }

    .btn:focus {
        outline: none;
        box-shadow: none;
    }
</style>{% endblock %} {% block title %}{{title}}{% endblock %} {% block content %}

<div class="row g-0">
    <div class="col-2 col1">
        <div class="card m-2 bg-light shadow text-center">
            <h5 class="card-header">Air Pressure</h5>
            <div class="card-body">
                <p id="press" class="d-inline">{{data['kitchen/temphumidpress']['Airpressure']|round(1)}}</p>hPa
            </div>
        </div>
        <div class="card m-2 bg-light shadow text-center">
            <h5 class="card-header">Humidity</h5>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Kitchen:
                    <p id="khumid" class="d-inline">{{data['kitchen/temphumidpress']['Humidity']|round(1)}}</p>%
                </li>
                <li class="list-group-item">Balcony:
                    <p id="bhumid" class="d-inline">{{data['balcony/temphumid']['Humidity']|round(1)}}</p>%
                </li>
            </ul>
        </div>
        <div class="card m-2 bg-light shadow text-center">
            <h5 class="card-header">Temperatures</h5>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Kitchen:
                    <p id="ktemp" class="d-inline">{{data['kitchen/temphumidpress']['Temperature']|round(1)}}</p>°C
                </li>
                <li class="list-group-item">Balcony:
                    <p id="btemp" class="d-inline">{{data['balcony/temphumid']['Temperature']|round(1)}}</p>°C
                </li>
                <li class="list-group-item">Outdoors:
                    <p id="otemp" class="d-inline">{{data['bikeroom/temp']['Temperature']|round(1)}}</p>°C
                </li>
            </ul>
        </div>
    </div>
    <div class="col-2 col2">
        <div class="card-group mt-2 shadow text-center" style="width: 24rem;">
            <div class="card">
                <div class="card-header h6">Full light</div>
                <div class="card-body" id="full_light_status">{{rel_status[0]}}</div>
            </div>
            <div class="card">
                <div class="card-header h6">Low light</div>
                <div class="card-body" id="low_light_status">{{rel_status[1]}}</div>
            </div>
            <div class="card">
                <div class="card-header h6">Heater</div>
                <div class="card-body" id="heater_status">{{rel_status[2]}}</div>
            </div>
        </div>
        {% if local %}
        <div class="btn-group mt-2" role="group" style="width: 18rem;">
            <button type="button" class="btn btn-warning cbutton" id="full_light" value="on">Full light</button>
            <button type="button" class="btn btn-warning cbutton" id="low_light" value="on">Low light</button>
            <button type="button" class="btn btn-warning cbutton" id="heater" value="on">Heater</button>
        </div><br style="clear: both;">
        <div class="btn-group mt-2" role="group" style="width: 24rem;">
            <button type="button" class="btn btn-danger cbutton text-dark" id="full_light" value="off">Full light
                off</button>
            <button type="button" class="btn btn-danger cbutton text-dark" id="low_light" value="off">Low light
                off</button>
            <button type="button" class="btn btn-danger cbutton text-dark" id="heater" value="off">Heater off</button>
            <button type="button" class="btn btn-danger cbutton text-dark" id="alloff" value="off">Everything
                off</button>
        </div>
        <div class="card mt-2 success" style="width: 12rem;">
            <div class="card-body h5">Command sent.</div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %} {% block script %} {% if local %}
<script type="text/javascript">
    $(".cbutton").click(function () {
        $.ajax({
            type: "POST",
            url: "{{ url_for('views.post_command') }}",
            data: {
                entity: $(this).attr('id'),
                command: $(this).val()
            },
            success: function () {
                $("div.success").fadeIn(300).delay(2500).fadeOut(500);
                setTimeout(function () {
                    $.getJSON("{{ url_for('views.home_status') }}", function (data) {
                        get_relay_status(data);
                    });
                }, 500);
            }
        });
        return false;
    });
    setInterval(function () {
        $.getJSON("{{ url_for('views.home_status') }}", function (data) {
            var decimals = 1;
            var dat = data['weather_data']
            document.getElementById("press").innerHTML = round_decimals(dat['kitchen/temphumidpress']['Airpressure'], decimals);
            document.getElementById("khumid").innerHTML = round_decimals(dat['kitchen/temphumidpress']['Humidity'], decimals);
            document.getElementById("ktemp").innerHTML = round_decimals(dat['kitchen/temphumidpress']['Temperature'], decimals);
            document.getElementById("btemp").innerHTML = round_decimals(dat['balcony/temphumid']['Temperature'], decimals);
            document.getElementById("bhumid").innerHTML = round_decimals(dat['balcony/temphumid']['Humidity'], decimals);
            document.getElementById("otemp").innerHTML = round_decimals(dat['bikeroom/temp']['Temperature'], decimals);
            get_relay_status(data);
        });
    }, 5000);
    function round_decimals(value, decimals) {
        return Math.round(value * 10 * decimals) / (10 * decimals);
    }
    function get_relay_status(data) {
        var i = 0;
        ["full_light_status", "low_light_status", "heater_status"].forEach(element => {
            var htmlelem = document.getElementById(element);
            var boolval = data['relay_status'][i] <= 0;
            if (boolval) htmlelem.className = "card-body bg-danger";
            else htmlelem.className = "card-body bg-success";
            htmlelem.innerHTML = boolval ? "Inactive" : "Active";
            i++;
        });
    }
    document.addEventListener("DOMContentLoaded", function () {
        get_relay_status(JSON.parse('{"relay_status":{{rel_status | tojson}}}'));
    });
</script>{%endif%} {% endblock %}

flask_home_app/webapp/backend/templates/notes.html
{% extends "base.html" %} {% block header %} {% if local %}
<style>
    .colf {
        width: 460px;
    }

    .btn:focus {
        outline: none;
        box-shadow: none;
    }
</style>{% endif %} {% endblock %} {% block title %}{{title}}{% endblock %} {% block content %} {% if local %}
<div class="row g-0">
    <div id="col" class="col-0 colf">
        <div id="scroller">
            <template id="post_template">
                <div class="card m-2 shadow collapse" id="post_id" aria-expanded="false">
                    <h5 class="card-header"><span id="post_time"></span><span id="post_number"
                            class="d-inline text-muted float-end" style="font-size: small;"></span></h5>
                    <div id="post_text" class="card-body"></div>
                    <div class="card-footer">
                        <div class="btn-group" role="group">
                            <button id="delpost" type="button" class="btn btn-danger"
                                onclick="delpost(this.value)">Delete</button>
                            <button id="editpost" type="button" class="btn btn-info" onclick="editpost(this.value)">Edit
                                Post</button>
                        </div>
                    </div>
                </div>
            </template>
        </div>
        <div class="d-flex justify-content-center my-3" id="sentinel">
            <div role="status"></div>
        </div>
    </div>
    <div id="col" class="col-0 colf">
        <div class="card sticky-top mt-2 shadow">
            <h5 class="card-header d-inline">Add post</h5>
            <div class="card-body" style="float:right;">
                <textarea id="posttext" class="form-control fs-5" placeholder="Text here" style="resize: none;"
                    rows=8></textarea>
            </div>
            <div class="card-footer text-muted">
                <button id="postbtn" class="btn btn-primary" style="float: right;">Post</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="editmodal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="edit_title"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <textarea id="edit_text" class="form-control fs-5" style="resize: none;" rows=8></textarea>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button class="btn btn-primary" id="savebtn">Save changes</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="delmodal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deltitle">Delete note</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body h6">
                Are you sure? Can't be undone!
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button class="btn btn-danger" id="delbtn">Delete note</button>
            </div>
        </div>
    </div>
</div>

{% else %}
<div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
    <div class="card-header m-3">
        <h5 class="card-title">Only accessible from local network!</h5>
    </div>
</div>
{%endif%} {% endblock %} {% block script %} {% if local %}
<script type="text/javascript">
    var sentinel = document.getElementById("sentinel");
    var counter = 0;
    function delpost(value) {
        var id = value.replace("pid", "");
        document.getElementById("delbtn").value = id;
        $("#delmodal").modal("show");
    };
    $("#delbtn").click(function () {
        this.disabled = true;
        var id = parseInt(this.value);
        var post_time_key = $("#pid" + id).attr("value");
        fetch("{{url_for('views.notes_api')}}", {
            method: "DELETE",
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ time_key: post_time_key }),
        }).then(response => {
            if (response.ok) alert("Deleting note failed")
            else {
                $(".modal").modal("hide");
                alert("Note successfully deleted")
                this.disabled = false;
                var hide_item = document.getElementById("pid" + id);
                new bootstrap.Collapse(hide_item, "hide");
                console.log(hide_item);
                hide_item.querySelectorAll('[id]').forEach(elem => elem.removeAttribute("id"));
                hide_item.querySelectorAll("button").forEach(elem => elem.removeAttribute("onclick"));
                hide_item.removeAttribute("id");
                next = hide_item.nextElementSibling;
                while(next !== null) {
                    var i = parseInt(next.id.replace("pid",""))
                    next.querySelector("#pn" + i).innerHTML = "#" + (i);
                    next.querySelectorAll('[id]').forEach(elem => elem.id = elem.id.replace(i, (i-1)));
                    next.querySelectorAll("button").forEach(b => b.value = b.value.replace(i, (i-1)));
                    next.id = next.id.replace(i, (i-1));
                    next = next.nextElementSibling;
                }
                counter--;
            }
        });

    });
    function editpost(value) {
        var id = value.replace("pid", "");
        document.getElementById("edit_text").value =
            document.getElementById("ptext" + id).innerHTML.replaceAll("<br>", "\n");
        document.getElementById("savebtn").value = id;
        document.getElementById("edit_title").innerHTML = "Edit note: " + document.getElementById("ptime" + id).innerHTML;
        $("#editmodal").modal("show");
    };
    $("#savebtn").click(function () {
        var formdata = document.getElementById("edit_text").value;
        if (formdata.length <= 1) {
            alert("Please enter text!");
            return;
        }
        this.disabled = true;
        var id = this.value;
        var post_time_key = $("#pid" + id).attr("value");
        fetch("{{url_for('views.notes_api')}}", {
            method: "PATCH",
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ time_key: post_time_key, text: formdata }),
        }).then(response => {
            if (!response.ok) alert("Updating note failed")
            else {
                $(".modal").modal("hide");
                alert("Note successfully submitted")
                this.disabled = false;
                document.getElementById("ptext" + id).innerHTML = formdata.replace(/\n/g, "<br />");
            }
        });
    });
    $("#postbtn").click(function () {
        var formdata = document.getElementById("posttext").value;
        if (formdata.length <= 1) {
            alert("Please enter text!");
            return;
        }
        this.disabled = true;
        fetch("{{url_for('views.notes_api')}}", {
            method: "POST",
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ newpost: formdata }),
        }).then(response => {
            if (response.status !== 200) alert("Submitting post failed")
            else {
                document.getElementById("posttext").value = "";
                alert("Note successfully submitted")
                response.json().then(data => {
                    add_post(data);
                    this.disabled = false;
                });
            }
        });
    });
    function loadItems() {
        fetch(`{{url_for('views.notes_api')}}?c=${counter}`).
            then((response) => {
                response.json().then((data) => {
                    //if (data.length < 10) sentinel.innerHTML = "No more posts";
                    for (var i = 0; i < data.length; i++) {
                        add_post(data[i]);
                    }
                });
            });
    };
    function add_post(data) {
        // No easier way? I want to keep id's unique.
        document.getElementById("scroller").appendChild(document.getElementById("post_template").content.cloneNode(true));
        $("#post_time").text(data.time).attr("id", "ptime" + counter);
        $("#post_number").text("#" + (counter + 1)).attr("id", "pn" + counter);
        document.getElementById("post_text").innerHTML = data.text.replace(/\n/g, "<br />")
        document.getElementById("post_text").id = "ptext" + counter;
        $("#delpost").attr("value", "pid" + counter).attr("id", "dp" + counter);
        $("#editpost").attr("value", "pid" + counter).attr("id", "ep" + counter);
        new bootstrap.Collapse(document.getElementById("post_id"), "show");
        $("#post_id").attr("value", data.time_key).attr("id", "pid" + counter);
        counter++;
    };
    const observer = new IntersectionObserver(entries => {
        if (entries[0].intersectionRatio <= 0) return;
        loadItems();
    });
    observer.observe(sentinel);
</script>
{%endif%} {% endblock %}